/**
 * Bundled 3D LUT looks (`public/luts/*.cube`, generated by scripts/gen-luts.mjs)
 * plus helpers shared by the export (ffmpeg `lut3d`) and the preview (a packed
 * Hald-CLUT texture sampled in the grade shader), so a look renders identically
 * in both. Custom imported LUTs reuse the same path under a `custom:` id.
 */
export interface LutLook {
  id: string;
  label: string;
  category: string;
}

// Bundled looks. ids are stable (saved in projects) and must match the cubes +
// thumbnails generated by scripts/gen-luts.mjs. The lut.test drift guard fails
// if a look here is missing its .cube or thumbnail on disk.
export const LUT_LOOKS: LutLook[] = [
  { id: 'cinematic', label: 'Cinematic', category: 'Film' },
  { id: 'tealorange', label: 'Teal & Orange', category: 'Film' },
  { id: 'bleach', label: 'Bleach', category: 'Film' },
  { id: 'noir', label: 'Noir', category: 'Mono' },
  { id: 'mono', label: 'Mono', category: 'Mono' },
  { id: 'ink', label: 'Ink', category: 'Mono' },
  { id: 'portrait', label: 'Portrait', category: 'Portrait' },
  { id: 'glow', label: 'Glow', category: 'Portrait' },
  { id: 'rosy', label: 'Rosy', category: 'Portrait' },
  { id: 'faded', label: 'Faded', category: 'Vintage' },
  { id: 'vintage', label: 'Vintage', category: 'Vintage' },
  { id: 'sepia', label: 'Sepia', category: 'Vintage' },
  { id: 'vivid', label: 'Vivid', category: 'Vibrant' },
  { id: 'punch', label: 'Punch', category: 'Vibrant' },
  { id: 'y2k', label: 'Y2K', category: 'Vibrant' },
  { id: 'cool', label: 'Cool', category: 'Cool' },
  { id: 'arctic', label: 'Arctic', category: 'Cool' },
  { id: 'warm', label: 'Warm', category: 'Warm' },
  { id: 'golden', label: 'Golden', category: 'Warm' },
  { id: 'sunset', label: 'Sunset', category: 'Warm' },
  { id: 'appetite', label: 'Appetite', category: 'Food' },
  { id: 'fresh', label: 'Fresh', category: 'Food' },
  { id: 'moody', label: 'Moody', category: 'Scenery' },
  { id: 'azure', label: 'Azure', category: 'Scenery' },
];

/** Display order of look categories in the Filters panel. */
export const LUT_CATEGORIES = [
  'Film',
  'Mono',
  'Portrait',
  'Vintage',
  'Vibrant',
  'Cool',
  'Warm',
  'Food',
  'Scenery',
] as const;

export interface LutCategoryGroup {
  category: string;
  looks: LutLook[];
}

/** Bundled looks grouped by category in display order (empty groups dropped). */
export function lutsByCategory(): LutCategoryGroup[] {
  return LUT_CATEGORIES.map((category) => ({
    category,
    looks: LUT_LOOKS.filter((l) => l.category === category),
  })).filter((g) => g.looks.length > 0);
}

export function lutLook(id?: string | null): LutLook | undefined {
  return id ? LUT_LOOKS.find((l) => l.id === id) : undefined;
}

/** True for a user-imported LUT id (vs. a bundled one). */
export function isCustomLut(id: string): boolean {
  return id.startsWith('custom:');
}

const UNSAFE = /[^a-z0-9_-]/gi;

/** Stable ffmpeg.wasm FS filename for a LUT id, used by the command builder and the runner. */
export function lutFileName(id: string): string {
  return `lut_${id.replace(UNSAFE, '_')}.cube`;
}

/** Public URL of a bundled LUT cube, or null for a custom (locally-held) LUT. */
export function lutUrl(id: string): string | null {
  if (isCustomLut(id)) return null;
  return `${import.meta.env.BASE_URL}luts/${id}.cube`;
}

/** Public URL of a bundled look's preview thumbnail, or null for a custom LUT. */
export function lutThumbUrl(id: string): string | null {
  if (isCustomLut(id)) return null;
  return `${import.meta.env.BASE_URL}luts/thumbs/${id}.png`;
}

/** The ungraded sample thumbnail, shown for the "None" (no look) option. */
export const LUT_ORIGINAL_THUMB = `${import.meta.env.BASE_URL}luts/thumbs/_original.png`;

const clamp01 = (x: number) => (x < 0 ? 0 : x > 1 ? 1 : x);

export interface ParsedCube {
  size: number;
  /** size^3 * 3 floats, red varying fastest (standard .cube ordering). */
  data: Float32Array;
}

/** Parse an Adobe `.cube` 3D LUT (ignores comments, TITLE and DOMAIN_* lines). */
export function parseCube(text: string): ParsedCube {
  let size = 0;
  const vals: number[] = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    if (line.startsWith('LUT_3D_SIZE')) {
      size = parseInt(line.split(/\s+/)[1], 10);
      continue;
    }
    if (/^[A-Za-z_]/.test(line)) continue; // TITLE, DOMAIN_MIN/MAX, LUT_1D_*, etc.
    const parts = line.split(/\s+/).map(Number);
    if (parts.length >= 3 && parts.slice(0, 3).every((n) => Number.isFinite(n))) {
      vals.push(parts[0], parts[1], parts[2]);
    }
  }
  if (!Number.isFinite(size) || size < 2 || size > 64 || vals.length !== size * size * size * 3) {
    throw new Error('Invalid .cube file');
  }
  return { size, data: Float32Array.from(vals) };
}

export interface PackedLut {
  width: number;
  height: number;
  size: number;
  pixels: Uint8Array;
}

/**
 * Pack a parsed cube into a 2D RGB byte texture: `size` blue slices laid out
 * left-to-right, each a size×size tile (red = x within the tile, green = y). The
 * grade shader samples this with bilinear red/green and manual blue blending.
 */
export function packLut({ size, data }: ParsedCube): PackedLut {
  const width = size * size;
  const height = size;
  const pixels = new Uint8Array(width * height * 3);
  for (let b = 0; b < size; b++) {
    for (let g = 0; g < size; g++) {
      for (let r = 0; r < size; r++) {
        const src = (r + g * size + b * size * size) * 3;
        const dst = (g * width + (b * size + r)) * 3;
        pixels[dst] = Math.round(clamp01(data[src]) * 255);
        pixels[dst + 1] = Math.round(clamp01(data[src + 1]) * 255);
        pixels[dst + 2] = Math.round(clamp01(data[src + 2]) * 255);
      }
    }
  }
  return { width, height, size, pixels };
}
